force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <description>This tab is for the users who will attend the users</description>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeRegistrationCustomController.cls
/**
This is a custom controller for Attendee Registration for an Event
*/
public with sharing class AttendeeRegistrationCustomController {

    
    // Instance variables for the controller
    public Event_Attendee__c eventAttendee{get; set;}
    public Attendees__c attendee{get; set;}
    public Location_Address_Book__c locationAttendee{get; set;}
    
    public String getid;


    // Constructor method to initialize instance variables and get the Event ID from the URL parameter
    public AttendeeRegistrationCustomController() {
        eventAttendee = new Event_Attendee__c();
        attendee = new Attendees__c();
        // locationAttendee = new Location_Address_Book__c();
        getid = Apexpages.currentPage().getParameters().get('value');
        
        // Set the Event ID for the Event_Attendee__c record
        if(getid != null){
            eventAttendee.Event__c = getid;
        }
        
    }


    /**
    Method to save the Event Attendee registration details
    */
    public void saveRecord(){

        // Create a save point to roll back if there's an exception
        Savepoint sp = Database.setSavePoint();

        try {

            insert locationAttendee;
            // Set the Address__c field on the Attendees__c record to the ID of the Location_Address_Book__c record
            attendee.Address__c = locationAttendee.id;
            // Insert the Attendees__c record
            insert attendee;
            
            // Set the Attendees__c field on the Event_Attendee__c record to the ID of the Attendees__c record
           eventAttendee.Attendees__c = attendee.id;
            // Insert the Event_Attendee__c record
            insert eventAttendee;

            // Clear the instance variables for a new registration
            locationAttendee = new Location_Address_Book__c();
            attendee = new Attendees__c();
            // eventAttendee = new Event_Attendee__c();

            

        } catch (Exception e) {

             // Catch any exceptions, log the error message, insert error records, and rollback to the save point
             System.debug('The following exception has occurred: ' + e.getMessage());

             // call the ErrorLogObject class method to store the error
             ErrorLogObject.insertErrorRecords(e.getMessage(), 'error occured');

             // Rollback, if there is any exception occur in the between
             Database.rollback(sp);
        }

    }

}